import { motion } from "framer-motion";

export function Hero() {
  return (
    <section className="relative min-h-[100vh] flex flex-col md:flex-row items-center justify-center p-4 pt-32 overflow-hidden max-w-7xl mx-auto gap-8 md:gap-16">
      {/* Animated Background Orbs */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none -z-10">
        <motion.div
          animate={{
            scale: [1, 1.2, 1],
            x: [0, 50, 0],
            y: [0, -30, 0],
            rotate: [0, 90, 0]
          }}
          transition={{ duration: 20, repeat: Infinity, ease: "easeInOut" }}
          className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-500/10 dark:bg-blue-400/5 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            scale: [1, 1.5, 1],
            x: [0, -70, 0],
            y: [0, 50, 0],
            rotate: [0, -90, 0]
          }}
          transition={{ duration: 25, repeat: Infinity, ease: "easeInOut", delay: 2 }}
          className="absolute bottom-1/4 right-1/4 w-[30rem] h-[30rem] bg-purple-500/10 dark:bg-purple-400/5 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            scale: [1, 1.1, 1],
            x: [0, 30, 0],
            y: [0, 40, 0]
          }}
          transition={{ duration: 15, repeat: Infinity, ease: "easeInOut", delay: 1 }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[40rem] h-[40rem] bg-indigo-500/5 dark:bg-indigo-400/5 rounded-full blur-[100px]"
        />
      </div>

      <motion.div 
        initial={{ opacity: 0, x: -30 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.8, ease: "easeOut" }}
        className="flex-1 text-center md:text-left z-10"
      >
        <h1 className="font-heading text-5xl sm:text-6xl md:text-7xl mb-6 tracking-tight leading-tight">
          AetherForge
        </h1>
        <p className="font-subheading text-xl sm:text-2xl opacity-80 mb-6 max-w-xl mx-auto md:mx-0 font-light leading-relaxed">
          Forged in the Aether – Code Without Noise.
        </p>
        <p className="text-base sm:text-lg opacity-60 max-w-lg mx-auto md:mx-0 font-normal">
          We build elegant, high-performance digital products with a strong focus on minimal interfaces and robust AI capabilities.
        </p>
        
        <div className="mt-10 flex flex-wrap gap-4 items-center justify-center md:justify-start">
          <motion.a 
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            href="#projects" 
            className="px-8 py-3 rounded-full bg-foreground text-background font-medium hover:opacity-90 transition-opacity"
          >
            Explore Work
          </motion.a>
          <motion.a 
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            href="#contact" 
            className="px-8 py-3 rounded-full border border-foreground/20 hover:bg-foreground/5 transition-colors font-medium"
          >
            Engage
          </motion.a>
        </div>
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, x: 30 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.8, delay: 0.2, ease: "easeOut" }}
        className="flex-1 flex justify-center z-10 mt-10 md:mt-0"
      >
        <div className="relative w-full max-w-md aspect-square">
          <div className="absolute inset-0 bg-gradient-to-tr from-blue-500/10 to-purple-500/10 rounded-full blur-2xl dark:opacity-50"></div>
          {/* We use hero-image.png which is generated by rembg */}
          <img 
            src="/hero-image.png" 
            alt="AetherForge Logo or Concept" 
            className="w-full h-full object-contain relative z-10 transform hover:scale-105 transition-transform duration-700 drop-shadow-2xl"
            onError={(e) => {
              // Fallback if rembg hasn't finished or failed
              e.target.onerror = null; 
              e.target.src = "/download (2).jfif";
              // CSS blend mode as a fallback just in case to help hide black/white backgrounds
              e.target.style.mixBlendMode = "luminosity"; 
            }}
          />
        </div>
      </motion.div>

    </section>
  );
}
